FROM apache/airflow:2.7.1-python3.9

USER root
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && apt-get clean

USER airflow
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
